## Standardise the feature values in the dataset

Scale the feature data points within the same scale

The following steps were carried out

- 1 Add the target dataset back into the feature dataset
- 2 Preparation of dataset for scaling
- 3 Carry out standardisation - via StandardScaler
- 4 Carry out standardisation - via MinMaxScaler
- 5 Decide and which standardised dataset to use

### 1 Add the target dataset back into the feature dataset

In [40]:
#verify the y values column (drivingStyle)
combined_y_values.shape

(23770,)

In [41]:
#verify the y values dataset (drivingStyle)

combined_y_values.describe

<bound method NDFrame.describe of 0        1
1        1
2        1
3        1
4        1
        ..
23765    1
23766    1
23767    1
23768    1
23769    1
Name: drivingStyle, Length: 23770, dtype: int8>

In [42]:
#add an index to the y values dataset

combined_y_values = combined_y_values.reset_index(drop=True)

In [43]:
#check dataset structure

combined_y_values.tail()

23765    1
23766    1
23767    1
23768    1
23769    1
Name: drivingStyle, dtype: int8

In [44]:
#need to add the target column back into the dataframe to allow for training/testing splits for model

df_no_outliers = pd.concat([df_no_outliers, combined_y_values], axis=1)

In [45]:
#check dataframe structure after adding target column back

df_no_outliers.shape

(23770, 16)

In [46]:
#statistical check of the updated dataframe

df_no_outliers.describe()

AltitudeVariation  VehicleSpeedInstantaneous  VehicleSpeedAverage  \
count       15062.000000               15062.000000         15062.000000   
mean           -0.320529                  29.279122            29.218030   
std             1.495935                  25.447507            21.251911   
min            -4.500000                   0.000000             0.000000   
25%            -1.200012                   5.400000            14.227623   
50%            -0.099976                  27.000000            24.422261   
75%             0.500000                  45.000000            40.828782   
max             3.800049                 119.570579           101.354997   

       VehicleSpeedVariance  VehicleSpeedVariation  LongitudinalAcceleration  \
count          15062.000000           15062.000000              15062.000000   
mean             145.174728               0.009229                  0.371484   
std              117.795082               1.434002                  0.868683   
min                0.000000              -3.600002                 -2.101800   
25%               50.828606              -0.900000                 -0.273000   
50%              113.302748               0.000000                  0.288000   
75%              212.241537               0.899998                  0.992100   
max              506.421168               3.600002                  3.171200   

         EngineLoad  EngineCoolantTemperature  ManifoldAbsolutePressure  \
count  15062.000000              15062.000000               15062.00000   
mean      32.548708                 71.816558                 109.14925   
std       24.586986                 13.027753                  10.69832   
min        0.000000                 36.000000                  88.00000   
25%       15.686275                 64.000000                 102.00000   
50%       29.411766                 79.000000                 105.00000   
75%       43.921570                 80.000000                 111.00000   
max      100.000000                 87.000000                 147.00000   

       IntakeAirTemperature  VerticalAcceleration  FuelConsumptionAverage  \
count          15062.000000          15062.000000            15062.000000   
mean              22.969858             -0.196887               15.486597   
std                9.339776              0.549763                4.118056   
min                8.000000             -1.740200                7.307876   
25%               16.000000             -0.528850               12.471350   
50%               20.000000             -0.085000               14.875591   
75%               30.000000              0.191400               18.232169   
max               53.000000              1.346200               28.054390   

                Car       Journey  drivingStyle  drivingStyle  
count  15062.000000  15062.000000  23770.000000  23770.000000  
mean       0.551188      2.463551      0.883929      0.883929  
std        0.497389      1.155625      0.320316      0.320316  
min        0.000000      1.000000      0.000000      0.000000  
25%        0.000000      1.000000      1.000000      1.000000  
50%        1.000000      3.000000      1.000000      1.000000  
75%        1.000000      3.000000      1.000000      1.000000  
max        1.000000      4.000000      1.000000      1.000000

In [47]:
#check the feature mean values

df_no_outliers.mean(axis=0) #check mean of each feature

AltitudeVariation             -0.320529
VehicleSpeedInstantaneous     29.279122
VehicleSpeedAverage           29.218030
VehicleSpeedVariance         145.174728
VehicleSpeedVariation          0.009229
LongitudinalAcceleration       0.371484
EngineLoad                    32.548708
EngineCoolantTemperature      71.816558
ManifoldAbsolutePressure     109.149250
IntakeAirTemperature          22.969858
VerticalAcceleration          -0.196887
FuelConsumptionAverage        15.486597
Car                            0.551188
Journey                        2.463551
drivingStyle                   0.883929
drivingStyle                   0.883929
dtype: float64

In [48]:
#check the feature std values

df_no_outliers.std(axis=0)#check standard deviation of each feature

AltitudeVariation              1.495935
VehicleSpeedInstantaneous     25.447507
VehicleSpeedAverage           21.251911
VehicleSpeedVariance         117.795082
VehicleSpeedVariation          1.434002
LongitudinalAcceleration       0.868683
EngineLoad                    24.586986
EngineCoolantTemperature      13.027753
ManifoldAbsolutePressure      10.698320
IntakeAirTemperature           9.339776
VerticalAcceleration           0.549763
FuelConsumptionAverage         4.118056
Car                            0.497389
Journey                        1.155625
drivingStyle                   0.320316
drivingStyle                   0.320316
dtype: float64

### 2 Preparation of datasets for scaling

In [49]:
#add required library

from sklearn.preprocessing import StandardScaler  #apply sklearn standardisation 

from sklearn.model_selection import train_test_split #used to create the training and test datasets

In [50]:
# split the dataframe

X = df_no_outliers.drop('drivingStyle', axis=1)

y = df_no_outliers['drivingStyle']

In [51]:
#separate the dataset into training and test datasets

# Split the data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [52]:
#check the shape of the X train & test dataframes

X_train.shape, X_test.shape

((16639, 14), (7131, 14))

### 3 Carry out standardisation - via StandardScaler

In [53]:

#standardisation using Standardscaler from Scikitlearn

scaler = StandardScaler()

#fit the scaler to train set, it will learn the parameters

scaler.fit(X_train)

#transform the train and test datasets

X_trained_scaled = scaler.transform(X_train)

X_test_scaled = scaler.transform(X_test)

In [54]:
#check the mean for each feature learned from the train set

scaler.mean_

array([-3.16838946e-01,  2.93723537e+01,  2.92179603e+01,  1.45341569e+02,
        1.08995839e-02,  3.71140443e-01,  3.24327071e+01,  7.17768407e+01,
        1.09169430e+02,  2.30727755e+01, -1.96223387e-01,  1.54774972e+01,
        5.50364825e-01,  2.46005875e+00])

In [55]:
#the scaler stores the standard deviation of the features learned from the train set

scaler.scale_

array([  1.4972894 ,  25.40846733,  21.26956931, 118.31044986,
         1.43069506,   0.87492102,  24.59525973,  13.05700228,
        10.69165473,   9.38668907,   0.55313043,   4.14192364,
         0.49745692,   1.15325317])

In [56]:
#transform the numpy arrays into dataframes to check the statistics

X_trained_scaled = pd.DataFrame(X_trained_scaled, columns=X_train.columns)

X_test_scaled = pd.DataFrame(X_test_scaled, columns=X_test.columns)

In [57]:
#check the structures

np.round(X_train.describe(),1)

AltitudeVariation  VehicleSpeedInstantaneous  VehicleSpeedAverage  \
count            10553.0                    10553.0              10553.0   
mean                -0.3                       29.4                 29.2   
std                  1.5                       25.4                 21.3   
min                 -4.5                        0.0                  0.0   
25%                 -1.2                        5.4                 14.3   
50%                 -0.1                       27.0                 24.4   
75%                  0.5                       45.0                 40.7   
max                  3.8                      119.6                101.4   

       VehicleSpeedVariance  VehicleSpeedVariation  LongitudinalAcceleration  \
count               10553.0                10553.0                   10553.0   
mean                  145.3                    0.0                       0.4   
std                   118.3                    1.4                       0.9   
min                     0.0                   -3.6                      -2.1   
25%                    50.5                   -0.9                      -0.3   
50%                   112.6                    0.0                       0.3   
75%                   213.0                    0.9                       1.0   
max                   506.4                    3.6                       3.2   

       EngineLoad  EngineCoolantTemperature  ManifoldAbsolutePressure  \
count     10553.0                   10553.0                   10553.0   
mean         32.4                      71.8                     109.2   
std          24.6                      13.1                      10.7   
min           0.0                      36.0                      88.0   
25%          15.3                      64.0                     102.0   
50%          29.4                      79.0                     105.0   
75%          43.5                      80.0                     111.0   
max         100.0                      87.0                     147.0   

       IntakeAirTemperature  VerticalAcceleration  FuelConsumptionAverage  \
count               10553.0               10553.0                 10553.0   
mean                   23.1                  -0.2                    15.5   
std                     9.4                   0.6                     4.1   
min                     8.0                  -1.7                     7.4   
25%                    16.0                  -0.5                    12.5   
50%                    20.0                  -0.1                    14.9   
75%                    30.0                   0.2                    18.3   
max                    53.0                   1.3                    28.0   

           Car  Journey  
count  10553.0  10553.0  
mean       0.6      2.5  
std        0.5      1.2  
min        0.0      1.0  
25%        0.0      1.0  
50%        1.0      3.0  
75%        1.0      3.0  
max        1.0      4.0

This scaling method did not standardise the means to 0 and the standard deviation to 1. So I will try to standardise the dataset using a different scaler

### 4 Carry out standardisation - via MinMaxScaler

In [58]:
#add required library

from sklearn.preprocessing import MinMaxScaler

In [59]:
#setup the scaler

scaler = MinMaxScaler()

#fit the scaler to the train set, it will learn the parameters

scaler.fit(X_train)

#transform train and test sets

X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [60]:
#the scaler stores the maximum values of the features learned from the train set

scaler.data_max_

array([  3.80004882, 119.5705795 , 101.3549971 , 506.4211679 ,
         3.60000229,   3.1712    , 100.        ,  87.        ,
       147.        ,  53.        ,   1.3462    ,  27.98824883,
         1.        ,   4.        ])

In [61]:
#the scaler stores the minimum values of the features learned from the train set

scaler.min_

array([ 0.54216549,  0.        ,  0.        ,  0.        ,  0.5       ,
        0.39859662,  0.        , -0.70588235, -1.49152542, -0.17777778,
        0.56382841, -0.35981991,  0.        , -0.33333333])

In [62]:
#the scaler also stores the value range (max - min)

scaler.data_range_

array([  8.30004882, 119.5705795 , 101.3549971 , 506.4211679 ,
         7.20000458,   5.273     , 100.        ,  51.        ,
        59.        ,  45.        ,   3.0864    ,  20.58232022,
         1.        ,   3.        ])

In [63]:
#transform the returned NumPy array to dataframes for further analysis

X_train_scaled = pd.DataFrame(X_train_scaled, columns=X_train.columns)
X_test_scaled = pd.DataFrame(X_test_scaled, columns=X_test.columns)

In [64]:
#check the original training dataset min & max values using np.round to reduce the number of decimal places to 1

np.round(X_train.describe(), 1)

AltitudeVariation  VehicleSpeedInstantaneous  VehicleSpeedAverage  \
count            10553.0                    10553.0              10553.0   
mean                -0.3                       29.4                 29.2   
std                  1.5                       25.4                 21.3   
min                 -4.5                        0.0                  0.0   
25%                 -1.2                        5.4                 14.3   
50%                 -0.1                       27.0                 24.4   
75%                  0.5                       45.0                 40.7   
max                  3.8                      119.6                101.4   

       VehicleSpeedVariance  VehicleSpeedVariation  LongitudinalAcceleration  \
count               10553.0                10553.0                   10553.0   
mean                  145.3                    0.0                       0.4   
std                   118.3                    1.4                       0.9   
min                     0.0                   -3.6                      -2.1   
25%                    50.5                   -0.9                      -0.3   
50%                   112.6                    0.0                       0.3   
75%                   213.0                    0.9                       1.0   
max                   506.4                    3.6                       3.2   

       EngineLoad  EngineCoolantTemperature  ManifoldAbsolutePressure  \
count     10553.0                   10553.0                   10553.0   
mean         32.4                      71.8                     109.2   
std          24.6                      13.1                      10.7   
min           0.0                      36.0                      88.0   
25%          15.3                      64.0                     102.0   
50%          29.4                      79.0                     105.0   
75%          43.5                      80.0                     111.0   
max         100.0                      87.0                     147.0   

       IntakeAirTemperature  VerticalAcceleration  FuelConsumptionAverage  \
count               10553.0               10553.0                 10553.0   
mean                   23.1                  -0.2                    15.5   
std                     9.4                   0.6                     4.1   
min                     8.0                  -1.7                     7.4   
25%                    16.0                  -0.5                    12.5   
50%                    20.0                  -0.1                    14.9   
75%                    30.0                   0.2                    18.3   
max                    53.0                   1.3                    28.0   

           Car  Journey  
count  10553.0  10553.0  
mean       0.6      2.5  
std        0.5      1.2  
min        0.0      1.0  
25%        0.0      1.0  
50%        1.0      3.0  
75%        1.0      3.0  
max        1.0      4.0

In [65]:
#check the scaled training dataset min & max values using np.round and 1 d.p

np.round(X_train_scaled.describe(), 1)

AltitudeVariation  VehicleSpeedInstantaneous  VehicleSpeedAverage  \
count            10553.0                    10553.0              10553.0   
mean                 0.5                        0.2                  0.3   
std                  0.2                        0.2                  0.2   
min                  0.0                        0.0                  0.0   
25%                  0.4                        0.0                  0.1   
50%                  0.5                        0.2                  0.2   
75%                  0.6                        0.4                  0.4   
max                  1.0                        1.0                  1.0   

       VehicleSpeedVariance  VehicleSpeedVariation  LongitudinalAcceleration  \
count               10553.0                10553.0                   10553.0   
mean                    0.3                    0.5                       0.5   
std                     0.2                    0.2                       0.2   
min                     0.0                    0.0                       0.0   
25%                     0.1                    0.4                       0.3   
50%                     0.2                    0.5                       0.5   
75%                     0.4                    0.6                       0.6   
max                     1.0                    1.0                       1.0   

       EngineLoad  EngineCoolantTemperature  ManifoldAbsolutePressure  \
count     10553.0                   10553.0                   10553.0   
mean          0.3                       0.7                       0.4   
std           0.2                       0.3                       0.2   
min           0.0                       0.0                       0.0   
25%           0.2                       0.5                       0.2   
50%           0.3                       0.8                       0.3   
75%           0.4                       0.9                       0.4   
max           1.0                       1.0                       1.0   

       IntakeAirTemperature  VerticalAcceleration  FuelConsumptionAverage  \
count               10553.0               10553.0                 10553.0   
mean                    0.3                   0.5                     0.4   
std                     0.2                   0.2                     0.2   
min                     0.0                   0.0                     0.0   
25%                     0.2                   0.4                     0.2   
50%                     0.3                   0.5                     0.4   
75%                     0.5                   0.6                     0.5   
max                     1.0                   1.0                     1.0   

           Car  Journey  
count  10553.0  10553.0  
mean       0.6      0.5  
std        0.5      0.4  
min        0.0      0.0  
25%        0.0      0.0  
50%        1.0      0.7  
75%        1.0      0.7  
max        1.0      1.0

The MinMaxScaler process converted max values have now been converted to 1 and then min values have been converted to 0. 